apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: cep-project1
  name: mypvc1
  labels:
    app: mydb1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi