apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: cep-project1
  name: mypvc2
  labels:
    app: wp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi